# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/snackademics',
                'doc_host': 'https://galopyz.github.io',
                'git_url': 'https://github.com/galopyz/snackademics',
                'lib_path': 'snackademics'},
  'syms': {'snackademics.core': {'snackademics.core.foo': ('core.html#foo', 'snackademics/core.py')}}}
